name: CD
on:
  deployment:
    types: published
  workflow_dispatch:
jobs:
  publish:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - name: Build and test
        shell: bash
        run: sbt publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
