# TBH: There's nothing of substance here with regards to testing.
# All this does is show is that sbt can build the project on various JVMs.

name: CI
on:
  pull_request:
  push:
    paths-ignore:
      - 'notebooks/*'
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
          - os: ubuntu-latest
            java: 17
          - os: windows-latest
            java: 17
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt
      - name: Build and test
        shell: bash
        run: sbt -v +test
